07/31/2017 14:34:20.326, setting both kts to volt source mode
07/31/2017 14:34:20.384, changing volt range on bias
07/31/2017 14:34:20.390, bias keithley volt zero and output on
07/31/2017 14:34:20.411, curr keithley volt zero and output on
07/31/2017 14:34:21.118, [Base        ] Leaving application in progress...
07/31/2017 14:34:21.141, stderr: 
07/31/2017 14:34:21.145, stderr: Traceback (most recent call last):
07/31/2017 14:34:21.151, stderr:   File "C:\Users\MOLNAR_PH330_D1\Desktop\NZERO\python_code\pstest.py", line 616, in <module>
07/31/2017 14:34:21.155, stderr:     NzeroApp().run()
07/31/2017 14:34:21.160, stderr:   File "C:\Python27\lib\site-packages\kivy\app.py", line 828, in run
07/31/2017 14:34:21.164, stderr:     runTouchApp()
07/31/2017 14:34:21.167, stderr:   File "C:\Python27\lib\site-packages\kivy\base.py", line 504, in runTouchApp
07/31/2017 14:34:21.171, stderr:     EventLoop.window.mainloop()
07/31/2017 14:34:21.176, stderr:   File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
07/31/2017 14:34:21.178, stderr:     self._mainloop()
07/31/2017 14:34:21.180, stderr:   File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 602, in _mainloop
07/31/2017 14:34:21.184, stderr:     self.modifiers):
07/31/2017 14:34:21.187, stderr:   File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8146)
07/31/2017 14:34:21.190, stderr:   File "kivy\_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy\_event.c:14035)
07/31/2017 14:34:21.193, stderr:   File "kivy\_event.pyx", line 1149, in kivy._event.EventObservers._dispatch (kivy\_event.c:13564)
07/31/2017 14:34:21.197, stderr:   File "C:\Python27\lib\site-packages\kivy\core\window\__init__.py", line 159, in _on_window_key_down
07/31/2017 14:34:21.200, stderr:     return self.dispatch('on_key_down', keycode, text, modifiers)
07/31/2017 14:34:21.203, stderr:   File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8146)
07/31/2017 14:34:21.206, stderr:   File "kivy\_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy\_event.c:14035)
07/31/2017 14:34:21.209, stderr:   File "kivy\_event.pyx", line 1149, in kivy._event.EventObservers._dispatch (kivy\_event.c:13564)
07/31/2017 14:34:21.211, stderr:   File "C:\Python27\lib\site-packages\kivy\uix\textinput.py", line 2438, in keyboard_on_key_down
07/31/2017 14:34:21.214, stderr:     self._key_down(key)
07/31/2017 14:34:21.217, stderr:   File "C:\Python27\lib\site-packages\kivy\uix\textinput.py", line 2300, in _key_down
07/31/2017 14:34:21.220, stderr:     self.dispatch('on_text_validate')
07/31/2017 14:34:21.223, stderr:   File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:8146)
07/31/2017 14:34:21.226, stderr:   File "kivy\_event.pyx", line 1225, in kivy._event.EventObservers.dispatch (kivy\_event.c:14035)
07/31/2017 14:34:21.230, stderr:   File "kivy\_event.pyx", line 1109, in kivy._event.EventObservers._dispatch (kivy\_event.c:12816)
07/31/2017 14:34:21.233, stderr:   File "C:\Python27\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback
07/31/2017 14:34:21.236, stderr:     exec(__kvlang__.co_value, idmap)
07/31/2017 14:34:21.239, stderr:   File "C:\Users\MOLNAR_PH330_D1\Desktop\NZERO\python_code\nzero.kv", line 103, in <module>
07/31/2017 14:34:21.242, stderr:     on_text_validate: root.process_input(ti.text); self.text = ''; root.set_focus_real();
07/31/2017 14:34:21.243, stderr:   File "C:\Users\MOLNAR_PH330_D1\Desktop\NZERO\python_code\pstest.py", line 106, in process_input
07/31/2017 14:34:21.246, stderr:     if tst.get_device(txt).get_stat1() not in ["o", "SC", "SCD", "SD"]:
07/31/2017 14:34:21.249, stderr:   File "C:\Users\MOLNAR_PH330_D1\Desktop\NZERO\python_code\test.py", line 112, in get_device
07/31/2017 14:34:21.253, stderr:     if ord(txt[0]) < 97:
07/31/2017 14:34:21.255, stderr: IndexError: string index out of range
